
services:
  backend:
    build: ./sealandBE
    container_name: backend
    restart: always
    env_file:
      - ./sealandBE/.env
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build: ./company-profile-sealand
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./company-profile-sealand/.env
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sealand
      MYSQL_USER: sealand
      MYSQL_PASSWORD: "Sealand@2025"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
