FROM node:20-alpine

WORKDIR /app

RUN npm config set registry https://registry.npmjs.org/
RUN npm config set fetch-retries 5
RUN npm config set fetch-retry-factor 2
RUN npm config set fetch-retry-mintimeout 20000
RUN npm config set fetch-retry-maxtimeout 120000

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build


EXPOSE 3000

CMD ["npm", "start"]
